import upperFirst from "../src/upperFirst.js";

describe("tests for upperFirst", () => {
    test("return given string with capitalized first letter", () => {
        expect(upperFirst("hello")).toBe("Hello");
        expect(upperFirst("world")).toBe("World");
    });

    test("return given string as is if all letters are already uppercase", () => {
        expect(upperFirst("HELLO")).toBe("HELLO");
        expect(upperFirst("WORLD")).toBe("WORLD");
    });

    test("return empty string when given an empty string", () => {
        expect(upperFirst("")).toBe("");
    });

    test("return empty string when given null", () => {
        expect(upperFirst(null)).toBe("");
    });

    test("return given string as is if the input contains numbers", () => {
        expect(upperFirst("123helloworld")).toBe("123helloworld");
    });

    test("throw error if input is not a string", () => {
        expect(() => upperFirst(123)).toThrow(TypeError);
    });
});

describe("additional tests, generated by AI (ChatGPT-5 model)", () => {

    // --- Basic behavior ---
    test("capitalizes the first letter of a lowercase word", () => {
        expect(upperFirst("hello")).toBe("Hello");
        expect(upperFirst("world")).toBe("World");
    });

    test("returns string unchanged if first letter is already uppercase", () => {
        expect(upperFirst("Hello")).toBe("Hello");
        expect(upperFirst("World")).toBe("World");
    });

    test("returns empty string when input is empty", () => {
        expect(upperFirst("")).toBe("");
    });

    test("returns empty string when input is null", () => {
        expect(upperFirst(null)).toBe("");
    });

    test("returns empty string when input is undefined", () => {
        expect(upperFirst(undefined)).toBe("");
    });


    // --- Non-letter first characters ---
    test("string starting with a number", () => {
        expect(upperFirst("1abc")).toBe("1abc");
        expect(upperFirst("123helloworld")).toBe("123helloworld");
    });

    test("string starting with a special character", () => {
        expect(upperFirst("#tag")).toBe("#tag");
        expect(upperFirst("_underscore")).toBe("_underscore");
        expect(upperFirst("!boom")).toBe("!boom");
    });

    test("string starting with whitespace", () => {
        expect(upperFirst(" hello")).toBe(" hello");
    });


    // --- Multi-word behavior ---
    test("capitalizes only the first character of the entire string", () => {
        expect(upperFirst("hello world")).toBe("Hello world");
        expect(upperFirst("a quick brown fox")).toBe("A quick brown fox");
    });

    test("does not affect words after the first", () => {
        expect(upperFirst("hello WORLD")).toBe("Hello WORLD");
    });


    // --- Unicode & special characters ---
    test("handles accented letters", () => {
        expect(upperFirst("éclair")).toBe("Éclair");
        expect(upperFirst("österreich")).toBe("Österreich");
    });

    test("handles emojis at the start", () => {
        expect(upperFirst("😀smile")).toBe("😀smile");
        expect(upperFirst("🎉party")).toBe("🎉party");
    });


    // --- Error handling ---
    test("throws TypeError when input is a number", () => {
        expect(() => upperFirst(123)).toThrow(TypeError);
    });

    test("throws TypeError when input is a boolean", () => {
        expect(() => upperFirst(true)).toThrow(TypeError);
    });

    test("throws TypeError when input is an object", () => {
        expect(() => upperFirst({})).toThrow(TypeError);
    });

    test("throws TypeError when input is an array", () => {
        expect(() => upperFirst([])).toThrow(TypeError);
    });

    test("throws TypeError when input is a symbol", () => {
        expect(() => upperFirst(Symbol("x"))).toThrow(TypeError);
    });


    // --- Edge cases ---
    test("single character lowercase", () => {
        expect(upperFirst("a")).toBe("A");
    });

    test("single character uppercase", () => {
        expect(upperFirst("A")).toBe("A");
    });

    test("whitespace-only string", () => {
        expect(upperFirst("   ")).toBe("   ");
    });

    test("string with newline at start", () => {
        expect(upperFirst("\nhello")).toBe("\nhello");
    });

    test("string with tab at start", () => {
        expect(upperFirst("\thello")).toBe("\thello");
    });

});